:sparkles: 实现基础的弹幕功能（暂不支持创作者彩虹弹幕）
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #109
Opened 2023-12-03 12:08 UTC by cfdxkk

:sparkles: 实现基础的弹幕功能（暂不支持创作者彩虹弹幕），修复一些问题

2023-12-03 12:44 UTC, otomad approved these changes

2023-12-03 12:48 UTC, otomad commented
缺省视频应该可以弄个假的发送（即仅在当前会话中弹幕可用，刷新页面后消失），不应提示弹幕发送失败。

2023-12-03 12:49 UTC, otomad requested changes
****

2023-12-05 13:40 UTC, cfdxkk commented
✨ 发送弹幕的请求不再阻塞。
1. 请求不再阻塞。用户发送弹幕后，页面中会实时出现用户发送的弹幕，而不是等待请求成功。
2. 可以在缺省视频中测试弹幕功能（但仍然会收到报错信息，因为 kvid 不合法）

2023-12-05 14:15 UTC, otomad approved these changes

2023-12-05 14:15 UTC, merged