:sparkles: 完善用户头像更新流程，现在可以上传用户本地的头像了
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #116
Opened 2023-12-30 09:22 UTC by cfdxkk

:sparkles: 完善用户头像更新流程，现在可以上传用户本地的头像了
新的头像更新流程和 twitter **几乎**一致

2023-12-30 10:23 UTC, otomad requested changes
请修改。

2023-12-30 10:23 UTC, otomad commented on pages/settings/profile.vue
> +			if (!/\.(gif|jpg|jpeg|png|bmp|GIF|JPG|PNG)$/.test(fileInput.value)) {
```suggestion
			if (!/\.(jpe?g|a?png|gif|bmp|webp|avif|heic|tiff?|svg)$/i.test(fileInput.value)) {
```

可使用 `i` 标志来忽略大小写，不必将各项的大小写都罗列一遍。

同时也添加了一些常见图片格式扩展名，检查一下是不是都支持？

2023-12-30 10:23 UTC, otomad commented on pages/settings/profile.vue
> +	const userAvatarFileInput = ref<HTMLElement>();
```suggestion
	const userAvatarFileInput = ref<HTMLInputElement>();
```

应该使用正确的类型声明。

2023-12-30 10:23 UTC, otomad commented on pages/settings/profile.vue
> +	});
可以使用 `useEventListener` 钩子简化操作（如果不会用可以忽略，我下次再改）。

2023-12-30 10:23 UTC, otomad commented on pages/settings/profile.vue
>  	const cropper = ref();
```suggestion
	const cropper = ref<InstanceType<typeof ImageCropper>>();
```

2023-12-30 10:23 UTC, otomad commented on pages/settings/profile.vue
> +			reader.readAsArrayBuffer(image);
```suggestion
			if (fileReaderEvent?.target?.result) {
				userUploadFile.value = fileToBlob(fileReaderEvent.target.result);
				avatarCropperIsOpen.value = true;
			}
```

原来写的有点绕圈了。

2023-12-30 10:23 UTC, otomad commented on pages/settings/profile.vue
> +		/>
```suggestion
		<input
			ref="userAvatarFileInput"
			type="file"
			accept="image/*"
			hidden
		/>
```

永远不要在 Vue 中这样写行内样式。

2023-12-30 16:20 UTC, otomad requested changes
已更新评论。

2023-12-30 16:20 UTC, otomad commented on pages/settings/profile.vue
> +		if (fileInput.files && fileInput.files?.[0]) {
```suggestion
		if (fileInput.files?.[0]) {
```

冗余的条件判断。

2023-12-30 16:20 UTC, otomad commented on pages/settings/profile.vue
> +		const fileInput = e?.target as HTMLInputElement;
```suggestion
		const fileInput = e.target as HTMLInputElement;
```

根据类型声明，形参 `e` 一定不为空，不必添加 `?`。

2023-12-30 16:20 UTC, otomad commented on pages/settings/profile.vue
>  		<div style="width: 20vw; height: 20vw;">
```suggestion
 		<div :style="{ width: '20dvw', height: '20dvw' }">
```

回去我找个 ESLint 规则把这种行内样式写法给毙了。

理论上现在改动的方法也不推荐，应该添加一个 class，然后在 `<style>` 里面编样式。

2023-12-30 16:20 UTC, otomad commented on pages/settings/profile.vue
> +	<Modal v-model="avatarCropperIsOpen" title="更新头像">
> _TODO: 使用多语言。_

2023-12-30 16:20 UTC, otomad commented on pages/settings/profile.vue
>  			const blobImageData = await cropper.value.getCropBlobData() as Blob;
建议检查一下 getCropBlobData 函数的类型声明，它是否会正确分析成 Blob 类型？理论上这里不应该出现类型断言。

2024-01-08 10:47 UTC, cfdxkk commented on pages/settings/profile.vue
>  			const blobImageData = await cropper.value.getCropBlobData() as Blob;
Fixed
移除了不必要的类型断言

2024-01-08 10:47 UTC, cfdxkk commented on pages/settings/profile.vue
> +	<Modal v-model="avatarCropperIsOpen" title="更新头像">
Fixed

2024-01-08 10:47 UTC, cfdxkk commented on pages/settings/profile.vue
>  		<div style="width: 20vw; height: 20vw;">
Fixed
不知道这么写好不好
``` html
<div class="avatar-cropper">
```
``` css
.avatar-cropper {
	--avatar-cropper-side-length: 350px;
	width: var(--avatar-cropper-side-length);
	height: var(--avatar-cropper-side-length);

	@media (width <= 450px) {
		--avatar-cropper-side-length: 80dvw; /// 对于图片切割器，不建议使用响应式，因为切割器内部被切割的图片不会随之改变尺寸，但考虑到极端小尺寸的适配问题，且只有极少数场景会改变浏览器宽度
	}
}
```

2024-01-08 10:50 UTC, cfdxkk commented on pages/settings/profile.vue
> +		const fileInput = e?.target as HTMLInputElement;
考虑到 HTML 元素和事件有可能因为各种原因为空，所以修改了函数的参数类型
多一层保险感觉安心一些
``` js
function handleOpenAvatarCropper(e?: Event) {
	const fileInput = e?.target as HTMLInputElement | undefined;
		if (fileInput?.files?.[0]) {
		...
		}
}
```

2024-01-08 10:50 UTC, cfdxkk commented on pages/settings/profile.vue
> +		if (fileInput.files && fileInput.files?.[0]) {
Fixed
详情见下

2024-01-08 10:50 UTC, cfdxkk commented on pages/settings/profile.vue
> +		/>
Fixed

2024-01-08 10:50 UTC, cfdxkk commented on pages/settings/profile.vue
> +			reader.readAsArrayBuffer(image);
Fixed

``` js
if (image) {
	userUploadFile.value = fileToBlob(image);
	avatarCropperIsOpen.value = true;
}
```

2024-01-08 10:51 UTC, cfdxkk commented on pages/settings/profile.vue
>  	const cropper = ref();
Fixed

2024-01-08 10:51 UTC, cfdxkk commented on pages/settings/profile.vue
> +	});
Fixed

2024-01-08 10:51 UTC, cfdxkk commented on pages/settings/profile.vue
> +	const userAvatarFileInput = ref<HTMLElement>();
Fixed

2024-01-08 10:51 UTC, cfdxkk commented on pages/settings/profile.vue
> +			if (!/\.(gif|jpg|jpeg|png|bmp|GIF|JPG|PNG)$/.test(fileInput.value)) {
![image](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/assets/41364445/2f275217-78ed-4004-93b8-bcb2f42bf310)

**虽然现在支持，但在 #123 后如果采用 Cloudflare Images 存储图片，bmp, avif, heic 和 tif(f) 将不受支持**

大小写问题已修复：
``` js
if (!/\.(a?png|gif|jpe?g|webp|svg)$/i.test(fileInput.value)) {
	useToast("只能上传图片文件！", "error"); // TODO 使用多语言
	console.error("ERROR", "上传的头像文件格式不合法！");
	return;
}
```

2024-01-08 10:58 UTC, cfdxkk commented
🐛 [修复](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/pull/116/commits/85cacfa171b1cc3dc8f9caf8513c46cf3b2cb614) 了一个用户无法重复上传（打开）同一个文件的问题

2024-01-08 11:41 UTC, otomad approved these changes

2024-01-08 11:41 UTC, merged