:construction: :recycle: :boom: [重大变更] 将存放 CSS 模板等数据的标签由 <html> 改为 .root-node, SSR 时正确渲染用户自定样式
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #130
Opened 2024-01-25 14:13 UTC by cfdxkk

:construction: :recycle: :boom: [重大变更]

1. 将存放 CSS 模板等数据的标签由 `<html></html>` 元素改为 app.vue 中的 `<div class="root-node"></div>`
2. 不再
```监听（watch） appSettings 状态库（pinia store）并使用 setClassEnabled(dom, ...) 方法来修改根节点的 class```
而是
```使用 Vue 模板语法动态改变 <div class="root-node"></div> 的 class```
使其在首屏 SSR 时能返回正确的文档，无需等待水和或 mounted
4. SSR 时正确渲染用户自定样式设置 [目前支持：彩色侧栏、动态背景、直角模式、扁平模式]
5. [副作用] 因为在 SSR 时已经请求用户数据，所以已登录用户在首屏渲染时，头像不再闪烁（由默认图标变为用户自定义头像）

注意：这不是一个合并到 develop 分支的 PR，仅供审阅重大变更事项。对于不优雅的代码，将会在正式合并至 develop 分支前在 [refactoring-2024012201-User_v2-cfdxkk](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/tree/refactoring-2024012201-User_v2-cfdxkk) 分支修正。

2024-01-25 16:02 UTC, otomad requested changes
我看不懂，但我大为震撼。

反正总感觉怪怪的。

还有Theme不是可以正确SSR吗？就ColoredSideBar不行，而且估计现在也不行。

2024-01-25 16:02 UTC, otomad commented on modules/unsupported-browsers/601.html
你怎么连601都改了？

2024-01-25 16:02 UTC, otomad commented on app.vue
> +	<div class="root-node" :class="{ sharp: appSettings.sharpAppearanceMode, flat: appSettings.flatAppearanceMode }">
为啥不用
```html
<div id="root">
```

2024-01-29 17:09 UTC, otomad commented
感觉移动根节点这个还是有点太离谱了，我以后想一个方法看看能否在保持 SSR 的基础上将属性添加到 \<html\> 上。
而且我赌所有的弹窗（如菜单、模态框等）都不会受到样式控制了，因为它们不在 Nuxt 内部的元素中。
我暂时先关闭吧，或者换一个更合适的支持 html 属性的 SSR 方式再开启。

2024-01-29 17:09 UTC, closed without merging

2024-01-29 17:17 UTC, Aira-Sakuranomiya commented
把这些全局用的class放body上可以吗，B站好像是这样的

2024-01-29 17:54 UTC, otomad commented
> 把这些全局用的class放body上可以吗，B站好像是这样的

理论上效果是一样的，HTML不行那body估计也不行。
另外这个全局class我是学的知乎，知乎就是把theme放在HTML上的。