🚧 ♻️ 💥 用户样式设置同步与持久化
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #132
Opened 2024-02-18 08:59 UTC by cfdxkk

🚧 ♻️ 💥 用户样式设置同步与持久化【重大变更】

① 解决所有可能的问题
② 强依赖于几个最新的后端 API，需要最新的与后端代码一同发布，在合共 PR 前通知。

2024-02-18 09:25 UTC, otomad requested changes
和 module 有关的代码都放在 module 里面吧，不要在其它地方直接 import 使用。

多用 composables useXXX 这种。

2024-02-18 09:25 UTC, otomad commented on app.vue
> +			},
要不单独整个computed变量放外面吧。

2024-02-18 09:25 UTC, otomad commented on composables/api/User/UserControllerDto.d.ts
呃，要不把type改成interface，要不保留分号。

我记得应该是规定如果是type，则应该有分号；

如果是interface，则不应有分号。

2024-02-18 09:25 UTC, otomad commented on layouts/settings.vue
> +	const htmlTitle = computed(() => title.value + " - " + t.settings); // BUG: Nuxt 在 3.9（或 @nuxtjs/i18n：8.0.0）开始 SSR 阶段无法渲染 `t.settings` （即“设置”字符串）致使报错，现通过如无法获取 Nuxt 对象时返回空字符串数据暂时修复，亟待正确的方法解决。
Nuxt 3.10 我这里看好像已经修好了啊？

2024-02-18 09:25 UTC, otomad commented on components/Login/LoginWindow.vue
> +	import { PALETTE_LIST } from "~/modules/theme/types";
跟 theme module 有关的代码都放在 module 里面吧，要不然 LoginWindow 组件这边的无关代码太乱了。

2024-02-18 09:25 UTC, otomad commented on middleware/cookie-baker.global.ts
> +import { PALETTE_LIST } from "~/modules/theme/types";
```typescript
"~/modules/theme/…
```
简写作
```typescript
"modules/theme/…
```
不要用vscode自动填充的 `~`。

2024-02-18 09:52 UTC, cfdxkk commented on composables/api/User/UserControllerDto.d.ts
vscode 不自动帮我补全分号了，以前还可以的，为什么？

2024-02-18 10:04 UTC, otomad commented on composables/api/User/UserControllerDto.d.ts
这个代码应该是你从后端自动同步过来的，可能后端的eslint和前端不一致。

2024-02-18 10:22 UTC, Aira-Sakuranomiya commented on layouts/settings.vue
> +	const htmlTitle = computed(() => title.value + " - " + t.settings); // BUG: Nuxt 在 3.9（或 @nuxtjs/i18n：8.0.0）开始 SSR 阶段无法渲染 `t.settings` （即“设置”字符串）致使报错，现通过如无法获取 Nuxt 对象时返回空字符串数据暂时修复，亟待正确的方法解决。
没，设置页面还是不能 SSR

2024-02-18 10:23 UTC, Aira-Sakuranomiya commented on layouts/settings.vue
> +	const htmlTitle = computed(() => title.value + " - " + t.settings); // BUG: Nuxt 在 3.9（或 @nuxtjs/i18n：8.0.0）开始 SSR 阶段无法渲染 `t.settings` （即“设置”字符串）致使报错，现通过如无法获取 Nuxt 对象时返回空字符串数据暂时修复，亟待正确的方法解决。
我群里刚才发了 KUN 说的，不应该在 utils 里用 useNuxtApp()

2024-02-18 10:24 UTC, cfdxkk commented on composables/api/User/UserControllerDto.d.ts
我复制粘贴过来的，eslint 确实不一样，后端的设置是不需要写分号
但是以前前端会检测到没写分号，然后在保存的时候自动补全

2024-02-18 11:24 UTC, otomad requested changes

2024-02-18 11:24 UTC, otomad commented on composables/api/User/UserController.ts
> +import type { CheckUserTokenResponseDto, GetSelfUserInfoRequestDto, GetSelfUserInfoResponseDto, GetUserAvatarUploadSignedUrlResultDto, GetUserInfoByUidRequestDto, GetUserInfoByUidResponseDto, GetUser
跟 theme module 有关的代码都放在 module 里面吧，理由同上。

2024-02-18 13:50 UTC, cfdxkk commented
@otomad 尽可能修复了发现的问题，并降低代码异味

2024-02-18 13:58 UTC, cfdxkk commented on composables/api/User/UserControllerDto.d.ts
已手动添加分号

2024-02-18 13:59 UTC, cfdxkk commented on app.vue
> +			},
Theme 整个删掉了，这一部分我也不要了

2024-02-20 10:23 UTC, otomad requested changes

2024-02-20 10:23 UTC, otomad commented on components/Login/LoginWindow.vue
> +	import { saveUserSetting2BrowserCookie } from "modules/theme/composables";
composables在module中我记得是有方法可以让他自动导入的，好像是useImport之类的。

2024-02-20 10:23 UTC, otomad commented on composables/api/User/UserController.ts
> +import type { CheckUserTokenResponseDto, GetSelfUserInfoRequestDto, GetSelfUserInfoResponseDto, GetUserAvatarUploadSignedUrlResultDto, GetUserInfoByUidRequestDto, GetUserInfoByUidResponseDto, GetUser
不是有一个后端的自动导入dts吗？放在里面就不需要再手动导入了，这太多了。

2024-02-20 10:34 UTC, cfdxkk commented on composables/api/User/UserController.ts
> +import type { CheckUserTokenResponseDto, GetSelfUserInfoRequestDto, GetSelfUserInfoResponseDto, GetUserAvatarUploadSignedUrlResultDto, GetUserInfoByUidRequestDto, GetUserInfoByUidResponseDto, GetUser
哪个里面我只放了全局使用的类型，不然那个文件里也会有很多很多导出

2024-02-20 17:48 UTC, otomad commented on composables/api/User/UserController.ts
> +import type { CheckUserTokenResponseDto, GetSelfUserInfoRequestDto, GetSelfUserInfoResponseDto, GetUserAvatarUploadSignedUrlResultDto, GetUserInfoByUidRequestDto, GetUserInfoByUidResponseDto, GetUser
可以用命名空间。

2024-02-20 17:48 UTC, otomad commented on composables/api/User/UserController.ts
> +import type { CheckUserTokenResponseDto, GetSelfUserInfoRequestDto, GetSelfUserInfoResponseDto, GetUserAvatarUploadSignedUrlResultDto, GetUserInfoByUidRequestDto, GetUserInfoByUidResponseDto, GetUser
哦不好意思，这是api后端代码，我看成其它地方前端代码使用了，还想怎么这么多import。

2024-02-21 13:29 UTC, cfdxkk commented on components/Login/LoginWindow.vue
> +	import { saveUserSetting2BrowserCookie } from "modules/theme/composables";
🖊️ Memo: 使用 nuxt kit 的 addImports 辅助函数可以显式添加一个全局导入。

2024-02-23 14:55 UTC, otomad requested changes
1. “cookieBinding.ts”建议修改为“cookie-binding.ts”有，因为它不是默认导出。
2. 注入的脚本名称 `COOKIE_BANDER_SCRIPT_TEMPLATE_NAME`“cookie-binding.js”含义似乎过于宽泛，不妨改为“theme-cookie-binding.js”？
3. 要不干脆把动态背景也加进去？

2024-02-23 14:59 UTC, Aira-Sakuranomiya commented
啊关于动态背景，这个之前开会的时候谈过，那次你没来。实验性设置不做同步，不然可能会出事。

2024-02-23 14:59 UTC, Aira-Sakuranomiya commented
> 3. 要不干脆把动态背景也加进去？


啊关于动态背景，这个之前开会的时候谈过，那次你没来。实验性设置不做同步，不然可能会出事。

2024-02-23 15:04 UTC, cfdxkk commented
> 1. “cookieBinding.ts”建议修改为“cookie-binding.ts”有，因为它不是默认导出。
> 2. 注入的脚本名称 `COOKIE_BANDER_SCRIPT_TEMPLATE_NAME`“cookie-binding.js”含义似乎过于宽泛，不妨改为“theme-cookie-binding.js”？
> 3. 要不干脆把动态背景也加进去？

1. `cookie-binding.ts` ok
2. cookieBinding 不一定绑定的是主题相关 cookie，以后可能会绑定其他用户设置
3. 建议以后再加，不想让这个分支太多修改。

2024-02-23 20:37 UTC, otomad commented
> > 3. 要不干脆把动态背景也加进去？
> 
> 
> 啊关于动态背景，这个之前开会的时候谈过，那次你没来。实验性设置不做同步，不然可能会出事。

但是直角模式和扁平模式都有，不如全加，反正一个变量的事。

2024-02-23 20:38 UTC, otomad commented
> > 1. “cookieBinding.ts”建议修改为“cookie-binding.ts”有，因为它不是默认导出。
> > 2. 注入的脚本名称 `COOKIE_BANDER_SCRIPT_TEMPLATE_NAME`“cookie-binding.js”含义似乎过于宽泛，不妨改为“theme-cookie-binding.js”？
> > 3. 要不干脆把动态背景也加进去？
> 
> 1. `cookie-binding.ts` ok
> 2. cookieBinding 不一定绑定的是主题相关 cookie，以后可能会绑定其他用户设置
> 3. 建议以后再加，不想让这个分支太多修改。

2. 但是这个cookie-binding放在了Theme module中，就很怪了。

2024-02-24 05:04 UTC, cfdxkk commented
> > > 1. “cookieBinding.ts”建议修改为“cookie-binding.ts”有，因为它不是默认导出。
> > > 2. 注入的脚本名称 `COOKIE_BANDER_SCRIPT_TEMPLATE_NAME`“cookie-binding.js”含义似乎过于宽泛，不妨改为“theme-cookie-binding.js”？
> > > 3. 要不干脆把动态背景也加进去？
> > 
> > 
> > 
> > 1. `cookie-binding.ts` ok
> > 2. cookieBinding 不一定绑定的是主题相关 cookie，以后可能会绑定其他用户设置
> > 3. 建议以后再加，不想让这个分支太多修改。
> 
> 2. 但是这个cookie-binding放在了Theme module中，就很怪了。

确实混乱，考虑暂时没有主题以外的设置，还是改成 `theme-cookie-binding.js` 好了

2024-02-24 05:08 UTC, cfdxkk commented
> > 3. 要不干脆把动态背景也加进去？
> 
> 啊关于动态背景，这个之前开会的时候谈过，那次你没来。实验性设置不做同步，不然可能会出事。

现在的程序，在偏好设置里有一个“是否开启同步”的开关。（目前，开启之后对：主题，个性色，彩色侧栏，直角模式，扁平模式的修改会同步到后端）
要改成实验模式里的所有设置项都不同步吗？

2024-02-24 05:46 UTC, otomad commented
> > > 3. 要不干脆把动态背景也加进去？
> > 
> > 啊关于动态背景，这个之前开会的时候谈过，那次你没来。实验性设置不做同步，不然可能会出事。
> 
> 现在的程序，在偏好设置里有一个“是否开启同步”的开关。（目前，开启之后对：主题，个性色，彩色侧栏，直角模式，扁平模式的修改会同步到后端）
> 要改成实验模式里的所有设置项都不同步吗？
> 
> 未来：由 WebSocket 之类技术来双工推送设置项更改，用户有以下两个选项：
> 1. 是否推送到其他设备    ←   现在只有这一个
> 2. 当前设备是否接受推送

要不改成实验性设置**全做同步**？

不过真的需要单独做同步设置开关吗？不如干脆简单点未登录用本地设置，已登录一律用云端设置更方便。

2024-02-24 05:46 UTC, cfdxkk commented
> > > 3. 要不干脆把动态背景也加进去？
> > 
> > 
> > 啊关于动态背景，这个之前开会的时候谈过，那次你没来。实验性设置不做同步，不然可能会出事。
> 
> 但是直角模式和扁平模式都有，不如全加，反正一个变量的事。

动态背景不是由 `<html></html>` 标签上的 class 控制的，添加的话可能需要额外步骤，我可以简单研究一下。

2024-02-24 05:51 UTC, Aira-Sakuranomiya commented
我觉得实验性设置全不做同步，里面的选项其实我都认为保留到正式版的可能性不大，不太可能真的会有普通用户喜欢。

2024-02-24 06:09 UTC, cfdxkk commented
> >...
> 要不改成实验性设置**全做同步**？
> 
> 不过真的需要单独做同步设置开关吗？不如干脆简单点未登录用本地设置，已登录一律用云端设置更方便。

实验模式还是挺“实验性”的
我一开动态背景大概率页面会卡死，或者是一些奇怪 glitch...
我发两个 issue
#133 #134

2024-02-24 08:45 UTC, otomad commented
> > >...
> > 要不改成实验性设置**全做同步**？
> > 
> > 不过真的需要单独做同步设置开关吗？不如干脆简单点未登录用本地设置，已登录一律用云端设置更方便。
> 
> 实验模式还是挺“实验性”的
> 我一开动态背景大概率页面会卡死，或者是一些奇怪 glitch...
> 我发两个 issue
> #133 #134 

实验性设置或者都先不同步，可仅本地保存。

等功能修复后可移出实验功能回到外观中。

2024-02-24 08:52 UTC, cfdxkk commented
...
> > 实验模式还是挺“实验性”的
> > 我一开动态背景大概率页面会卡死，或者是一些奇怪 glitch...
> > 我发两个 issue
> > #133 #134
> 
> 实验性设置或者都先不同步，可仅本地保存。
> 
> 等功能修复后可移出实验功能回到外观中。

已关闭实验性设置的多端同步功能

2024-02-24 10:21 UTC, otomad approved these changes

2024-02-25 03:23 UTC, merged

2024-02-25 03:25 UTC, cfdxkk commented
@otomad @Aira-Sakuranomiya 
Merged.
Thank you all.

back-end version sync success: [0.5.0](https://hub.docker.com/layers/cfdxkk01/kirakira/0.5.0/images/sha256-782577dc5c7d54dbed7205476adc4eb53f884004b7f136b09edf65136125e456?context=repo)