:sparkles: 新功能：浏览历史
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #170
Opened 2024-06-23 15:16 UTC by cfdxkk

:sparkles: 新功能：浏览历史
@otomad @Aira-Sakuranomiya

#### 测试焦点
* 视频浏览（历史）记录。
  * 能否正确记录用户浏览记录。
  * 关键词搜索功能是否工作正常（回车键搜索）。
  * 如果可能的话，需要在不同时区测试跨时区是否工作正常。
* 寻求外观改进建议。

#### 已知问题
* （不用修）没有上传者信息的视频，不会显示在浏览历史中。

#### 未包含功能
以下功能正在开发中，但并未能包含在本次更新中。
* 记录用户播放进度 / 在用户退出视频页或者关闭页面时记录。
* 使用视频标题之外的方式过滤。
* 日历功能。
* 其他类型的内容的浏览记录混入。

2024-06-23 15:48 UTC, otomad requested changes
还是建议改用 Intl.RelativeTimeFormat 而非手动本地化。

2024-06-23 15:48 UTC, otomad commented on composables/api/BrowsingHistory/BrowsingHistoryController.ts
> +const BROWSING_HISTORY_API_URI = `${BACK_END_URL}/history`;
URL 和 URI 名称是否应该统一？

2024-06-23 15:48 UTC, otomad commented on composables/api/BrowsingHistory/BrowsingHistoryControllerDto.ts
> +export type BROWSING_HISTORY_CATEGORY = "video" | "photo" | "comment";
类型名词应该改用大驼峰形式命名：
```suggestion
export type BrowsingHistoryCategory = "video" | "photo" | "comment";
```

2024-06-23 15:48 UTC, otomad commented on composables/api/BrowsingHistory/BrowsingHistoryControllerDto.ts
> +		& ThumbVideoResponseDto["videos"][number])[];
```suggestion
	result?: (
		& BrowsingHistory
		& {
			/** 最后更新时间 */
			lastUpdateDateTime: number;
		}
		& ThumbVideoResponseDto["videos"][number]
	)[];
```

2024-06-23 15:48 UTC, otomad commented on pages/history.vue
>  <script setup lang="ts">
还是建议改用 Intl.RelativeTimeFormat 而非手动本地化。

2024-07-02 12:04 UTC, cfdxkk commented on pages/history.vue
>  <script setup lang="ts">
Done!

2024-07-02 13:28 UTC, otomad approved these changes
👍

2024-07-02 14:14 UTC, Aira-Sakuranomiya approved these changes
お疲れ様です

2024-07-02 15:40 UTC, merged