fix(comment): optimize comment pagination logic
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #253
Opened 2024-09-16 09:36 UTC by AkutaZehy

Fix #252 lmao

2024-09-16 12:29 UTC, otomad commented
草，Math.floor(…+1) 是哪位甜菜写的？

2024-09-18 02:09 UTC, cfdxkk requested changes

2024-09-18 02:09 UTC, cfdxkk commented on components/Creation/CreationComments/CreationComments.vue
> +	const pageCount = computed(() => Math.ceil(commentsCount.value / pageSize));
`Math.ceil(0 / 20)` 仍会导致报错。
```suggestion
	const pageCount = computed(() => Math.max(1, Math.ceil(commentsCount.value / pageSize)));
```

2024-09-18 02:09 UTC, cfdxkk commented
thanks: @AkutaZehy @otomad
之前 `Math.ceil(0 / 20)` 时结果为零会报错，所以我[改成](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/commit/f23fc2b7e1eaa6d364642c2cf6f04ba2bae7013f)了：`Math.floor((0 / 20) + 1)` 。
但显然，在出现整除时也会出错....

综上，
1. 改为
    ```
    Math.max(1, Math.ceil(commentCount / 20));
    ```
2. 请全局搜索并检查其他使用分页器的页面，例如用户管理。

cc @Aira-Sakuranomiya

2024-09-18 02:11 UTC, AkutaZehy commented on components/Creation/CreationComments/CreationComments.vue
> +	const pageCount = computed(() => Math.ceil(commentsCount.value / pageSize));
我就知道这事没这么简单...

2024-09-18 02:19 UTC, cfdxkk commented
``` typescript
Math.ceil(commentCount / 20) || 1;
```
这么写也可以，嵌套少一些，语义差一些。
@otomad 你怎么看

2024-09-18 02:22 UTC, otomad commented
怎么说，我觉得直接修改 分页器 的逻辑更加合适。

直接在 分页器 里面对参数预处理一下。

这样你就可以直接用 `commentCount / 20` 了。

2024-09-18 02:25 UTC, cfdxkk commented
> 怎么说，我觉得直接修改 分页器 的逻辑更加合适。

分页器直接接受 总数 和 每页数量 两个参数，而不是接受 总数量 参数？

2024-09-18 02:32 UTC, otomad commented
> > 怎么说，我觉得直接修改 分页器 的逻辑更加合适。
> 
> 分页器直接接受 总数 和 每页数量 两个参数，而不是接受 总页数 参数？

也可以，最好两者可以同时支持。

可惜 Vue 不支持重载组件。

2024-09-18 02:33 UTC, AkutaZehy commented
> ```ts
> Math.ceil(commentCount / 20) || 1;
> ```
> 
> 这么写也可以，嵌套少一些，语义差一些。 @otomad 你怎么看

提问：我感觉后面这种看上去安全一点？🤔

会不会有`commentCount=undefined`或者`null`这种的情况？

2024-09-18 02:38 UTC, otomad commented
> 提问：我感觉后面这种看上去安全一点？🤔

不用这样，直接改分页器更方便。

2024-09-18 10:49 UTC, cfdxkk commented
对其他使用了翻页器的组件也做了类似修正。
``` typescript
const pageCount = computed(() => Math.max(1, Math.ceil(commentsCount.value / pageSize)));
```
对于翻页器组件的改进，需要进一步讨论。

@Aira-Sakuranomiya @otomad plz review

2024-09-20 09:27 UTC, Aira-Sakuranomiya commented
因为我对于翻页器组件的实现也不了解，还是需要 @otomad 来讨论

2024-09-22 09:42 UTC, cfdxkk commented
先把这个修复合并回去，至于组件的改进以后再说。
@otomad 麻烦尽快审查。

2024-10-03 09:19 UTC, merged