:sparkles: 恢复部分视频功能
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #94
Opened 2023-10-22 17:02 UTC by cfdxkk

恢复部分视频功能

2023-10-24 10:18 UTC, otomad requested changes
Please update [pages/home.vue](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/pull/94/files#diff-41317691c42b471ab8bc5f8b314f108f684ffec5b0be9af0022ff44f44b8b5a7) and [pages/video/kv[kvid].vue](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/pull/94/files#diff-4d00bb78be65eb0e88dfb3be860f9aef818c94ce3af06e7d1666fc549a8e8b1e).

2023-10-24 10:18 UTC, otomad commented on pages/video/kv[kvid].vue
>  		} catch (error) { handleError(error); }
这是因为之前会出现花括号单行、handleError未使用、异步未使用的警告，但我当时就是不想删掉，就写一些无用的代码（void 0相当于undefined）占位置防止eslint报红。

现在你写了新代码就可以删掉了。

2023-10-24 10:18 UTC, otomad commented on pages/home.vue
> +					"
在模板附标中可以使用注释？？？

2023-10-24 10:24 UTC, otomad requested changes
Update shibamata test video code line range.

2023-10-24 10:24 UTC, otomad commented on pages/video/kv[kvid].vue
> -		}
把检测到非infinite视频号时时，播放预设视频柴又，以免后端宕机时前端没有视频页面用于测试。

别删了。

2023-10-24 13:07 UTC, cfdxkk commented on pages/home.vue
> +					"
已改为 
```
:date="new Date(video.updateDate || 0)"
```

2023-10-24 13:08 UTC, cfdxkk commented on pages/video/kv[kvid].vue
> -		}
已添加渐进式增强

2023-10-25 00:59 UTC, otomad approved these changes
Done!

2023-10-25 01:01 UTC, merged