Upgrade to Nuxt 3.8.0
KIRAKIRA-DOUGA/KIRAKIRA-Cerasus pull request #95
Opened 2023-10-24 06:14 UTC by Aira-Sakuranomiya

2023-10-24 10:19 UTC, otomad requested changes
Please update [package.json](https://github.com/KIRAKIRA-DOUGA/KIRAKIRA-Cerasus/pull/95/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519).

2023-10-24 10:19 UTC, otomad commented on package.json
> -		"@nuxt/devtools": "^0.2.5",
@nuxt/devtools 呢？

2023-10-24 10:22 UTC, otomad requested changes

2023-10-24 10:22 UTC, otomad commented on locales/English.ts
> -import { LocaleIdentifiers } from "./types";
为什么只有英语和韩语添加了 type，其它语言呢？

2023-10-24 14:45 UTC, Aira-Sakuranomiya commented on package.json
> -		"@nuxt/devtools": "^0.2.5",
新版Nuxt中改为了自带，外置包应该移除了，详见 https://github.com/nuxt/nuxt/releases/tag/v3.8.0

2023-10-24 14:49 UTC, Aira-Sakuranomiya commented on locales/English.ts
> -import { LocaleIdentifiers } from "./types";
fixed

2023-10-25 00:58 UTC, otomad approved these changes
Done.

2023-10-25 01:01 UTC, merged